[start]
command:sh /usr/local/etc/rc.d/os-lucky onestart
parameters:
type:script
message:starting lucky

[stop]
command:sh /usr/local/etc/rc.d/os-lucky onestop
parameters:
type:script
message:stopping lucky

[restart]
command:sh /usr/local/etc/rc.d/os-lucky onerestart
parameters:
type:script
message:restarting lucky
description:Restart Lucky service

[status]
command:sh /usr/local/etc/rc.d/os-lucky status
parameters:
type:script_output
message:request lucky status
