[apply]
command:/usr/local/sbin/staticarpctl apply
parameters:
type:script_output
message:applying static ARP binding
description:Apply Static ARP Binding

[reset]
command:/usr/local/sbin/staticarpctl reset
parameters:
type:script_output
message:resetting static ARP binding
description:Reset Static ARP Binding

[status]
command:/usr/local/sbin/staticarpctl status
parameters:
type:script_output
message:request static ARP binding status
description:Static ARP Binding status
