#!/bin/sh

service configd restart >/dev/null 2>&1 || true
/usr/local/opnsense/scripts/firmware/register.php install os-unboundcustom >/dev/null 2>&1 || true
configctl template reload OPNsense/Unboundcustom >/dev/null 2>&1 || true
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml
configctl webgui restart >/dev/null 2>&1 || true
exit 0
