[start]
command:sh /usr/local/etc/rc.d/os-ddns-go onestart
parameters:
type:script
message:starting ddns-go

[stop]
command:sh /usr/local/etc/rc.d/os-ddns-go onestop
parameters:
type:script
message:stopping ddns-go

[restart]
command:sh /usr/local/etc/rc.d/os-ddns-go onerestart
parameters:
type:script
message:restarting ddns-go
description:Restart DDNS-Go service

[status]
command:sh /usr/local/etc/rc.d/os-ddns-go status
parameters:
type:script_output
message:request ddns-go status
