#!/bin/sh

rm -rf /usr/local/opnsense/scripts/ddclient/lib/__pycache__ /usr/local/opnsense/scripts/ddclient/lib/account/__pycache__
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml /var/lib/php/tmp/opnsense_acl_cache.json
service configd restart >/dev/null 2>&1 || true
/usr/local/opnsense/scripts/firmware/register.php install os-ddclient-opnwall >/dev/null 2>&1 || true
configctl template reload OPNsense/ddclient >/dev/null 2>&1 || true
configctl ddclient restart >/dev/null 2>&1 || true
exit 0
