[apply]
command:/usr/local/opnsense/scripts/OPNsense/Unboundcustom/apply.sh
parameters:
type:script_output
message:validate and apply Unbound custom options
description:Validate and apply Unbound custom options
